// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: client_server.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Alpha.Server {

  /// <summary>Holder for reflection information generated from client_server.proto</summary>
  public static partial class ClientServerReflection {

    #region Descriptor
    /// <summary>File descriptor for client_server.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientServerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNjbGllbnRfc2VydmVyLnByb3RvEgxhbHBoYS5zZXJ2ZXIaDGNvbW1vbi5w",
            "cm90bzKdAQoOSVNlcnZlclNlcnZpY2USSAoOY29ubmVjdF9zZXJ2ZXISIi5h",
            "bHBoYS5zZXJ2ZXIuQ29ubmVjdFNlcnZlclJlcXVlc3QaEi5hbHBoYS5zZXJ2",
            "ZXIuVm9pZBJBCg5lbnRpdHlfbWVzc2FnZRIbLmFscGhhLnNlcnZlci5FbnRp",
            "dHlNZXNzYWdlGhIuYWxwaGEuc2VydmVyLlZvaWQymgEKDklDbGllbnRTZXJ2",
            "aWNlEkUKDWNvbm5lY3RfcmVwbHkSIC5hbHBoYS5zZXJ2ZXIuQ29ubmVjdFNl",
            "cnZlclJlcGx5GhIuYWxwaGEuc2VydmVyLlZvaWQSQQoOZW50aXR5X21lc3Nh",
            "Z2USGy5hbHBoYS5zZXJ2ZXIuRW50aXR5TWVzc2FnZRoSLmFscGhhLnNlcnZl",
            "ci5Wb2lkQgOQAQFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Alpha.Server.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
