# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_gate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_gate.proto',
  package='alpha.server',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x63lient_gate.proto\x12\x0c\x61lpha.server\x1a\x0c\x63ommon.proto2\x9b\x01\n\x0cIGateService\x12H\n\x0e\x63onnect_server\x12\".alpha.server.ConnectServerRequest\x1a\x12.alpha.server.Void\x12\x41\n\x0e\x65ntity_message\x12\x1b.alpha.server.EntityMessage\x1a\x12.alpha.server.Void2\x97\x01\n\x0bIGateClient\x12\x45\n\rconnect_reply\x12 .alpha.server.ConnectServerReply\x1a\x12.alpha.server.Void\x12\x41\n\x0e\x65ntity_message\x12\x1b.alpha.server.EntityMessage\x1a\x12.alpha.server.VoidB\x03\x90\x01\x01\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_IGATESERVICE = _descriptor.ServiceDescriptor(
  name='IGateService',
  full_name='alpha.server.IGateService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=50,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='connect_server',
    full_name='alpha.server.IGateService.connect_server',
    index=0,
    containing_service=None,
    input_type=common__pb2._CONNECTSERVERREQUEST,
    output_type=common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='entity_message',
    full_name='alpha.server.IGateService.entity_message',
    index=1,
    containing_service=None,
    input_type=common__pb2._ENTITYMESSAGE,
    output_type=common__pb2._VOID,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IGATESERVICE)

DESCRIPTOR.services_by_name['IGateService'] = _IGATESERVICE


_IGATECLIENT = _descriptor.ServiceDescriptor(
  name='IGateClient',
  full_name='alpha.server.IGateClient',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=208,
  serialized_end=359,
  methods=[
  _descriptor.MethodDescriptor(
    name='connect_reply',
    full_name='alpha.server.IGateClient.connect_reply',
    index=0,
    containing_service=None,
    input_type=common__pb2._CONNECTSERVERREPLY,
    output_type=common__pb2._VOID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='entity_message',
    full_name='alpha.server.IGateClient.entity_message',
    index=1,
    containing_service=None,
    input_type=common__pb2._ENTITYMESSAGE,
    output_type=common__pb2._VOID,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IGATECLIENT)

DESCRIPTOR.services_by_name['IGateClient'] = _IGATECLIENT

IGateService = service_reflection.GeneratedServiceType('IGateService', (_service.Service,), dict(
  DESCRIPTOR = _IGATESERVICE,
  __module__ = 'client_gate_pb2'
  ))

IGateService_Stub = service_reflection.GeneratedServiceStubType('IGateService_Stub', (IGateService,), dict(
  DESCRIPTOR = _IGATESERVICE,
  __module__ = 'client_gate_pb2'
  ))


IGateClient = service_reflection.GeneratedServiceType('IGateClient', (_service.Service,), dict(
  DESCRIPTOR = _IGATECLIENT,
  __module__ = 'client_gate_pb2'
  ))

IGateClient_Stub = service_reflection.GeneratedServiceStubType('IGateClient_Stub', (IGateClient,), dict(
  DESCRIPTOR = _IGATECLIENT,
  __module__ = 'client_gate_pb2'
  ))


# @@protoc_insertion_point(module_scope)
