# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='alpha.server',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x0c\x61lpha.server\"\x06\n\x04Void\"\xab\x01\n\x14\x43onnectServerRequest\x12\x10\n\x08\x65ntityid\x18\x01 \x01(\t\x12\x10\n\x08\x63lientid\x18\x02 \x01(\t\x12\x0e\n\x06gateid\x18\x03 \x01(\t\x12<\n\x04type\x18\x04 \x01(\x0e\x32..alpha.server.ConnectServerRequest.RequestType\"!\n\x0bRequestType\x12\x12\n\x0eNEW_CONNECTION\x10\x00\"\xbf\x01\n\x12\x43onnectServerReply\x12\x10\n\x08\x65ntityid\x18\x01 \x01(\t\x12\x10\n\x08\x63lientid\x18\x02 \x01(\t\x12\x0e\n\x06gateid\x18\x03 \x01(\t\x12\x38\n\x04type\x18\x04 \x01(\x0e\x32*.alpha.server.ConnectServerReply.ReplyType\x12\x10\n\x08\x65xtramsg\x18\x05 \x01(\t\")\n\tReplyType\x12\r\n\tCONNECTED\x10\x00\x12\r\n\tFORBIDDEN\x10\x01\"E\n\rEntityMessage\x12\x10\n\x08\x65ntityid\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\tB\x03\x90\x01\x01\x62\x06proto3')
)



_CONNECTSERVERREQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='alpha.server.ConnectServerRequest.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW_CONNECTION', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=177,
  serialized_end=210,
)
_sym_db.RegisterEnumDescriptor(_CONNECTSERVERREQUEST_REQUESTTYPE)

_CONNECTSERVERREPLY_REPLYTYPE = _descriptor.EnumDescriptor(
  name='ReplyType',
  full_name='alpha.server.ConnectServerReply.ReplyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORBIDDEN', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=363,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_CONNECTSERVERREPLY_REPLYTYPE)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='alpha.server.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=36,
)


_CONNECTSERVERREQUEST = _descriptor.Descriptor(
  name='ConnectServerRequest',
  full_name='alpha.server.ConnectServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entityid', full_name='alpha.server.ConnectServerRequest.entityid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='alpha.server.ConnectServerRequest.clientid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gateid', full_name='alpha.server.ConnectServerRequest.gateid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='alpha.server.ConnectServerRequest.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONNECTSERVERREQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=210,
)


_CONNECTSERVERREPLY = _descriptor.Descriptor(
  name='ConnectServerReply',
  full_name='alpha.server.ConnectServerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entityid', full_name='alpha.server.ConnectServerReply.entityid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='alpha.server.ConnectServerReply.clientid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gateid', full_name='alpha.server.ConnectServerReply.gateid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='alpha.server.ConnectServerReply.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extramsg', full_name='alpha.server.ConnectServerReply.extramsg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONNECTSERVERREPLY_REPLYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=404,
)


_ENTITYMESSAGE = _descriptor.Descriptor(
  name='EntityMessage',
  full_name='alpha.server.EntityMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entityid', full_name='alpha.server.EntityMessage.entityid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='alpha.server.EntityMessage.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='alpha.server.EntityMessage.parameters', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=475,
)

_CONNECTSERVERREQUEST.fields_by_name['type'].enum_type = _CONNECTSERVERREQUEST_REQUESTTYPE
_CONNECTSERVERREQUEST_REQUESTTYPE.containing_type = _CONNECTSERVERREQUEST
_CONNECTSERVERREPLY.fields_by_name['type'].enum_type = _CONNECTSERVERREPLY_REPLYTYPE
_CONNECTSERVERREPLY_REPLYTYPE.containing_type = _CONNECTSERVERREPLY
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['ConnectServerRequest'] = _CONNECTSERVERREQUEST
DESCRIPTOR.message_types_by_name['ConnectServerReply'] = _CONNECTSERVERREPLY
DESCRIPTOR.message_types_by_name['EntityMessage'] = _ENTITYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:alpha.server.Void)
  ))
_sym_db.RegisterMessage(Void)

ConnectServerRequest = _reflection.GeneratedProtocolMessageType('ConnectServerRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTSERVERREQUEST,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:alpha.server.ConnectServerRequest)
  ))
_sym_db.RegisterMessage(ConnectServerRequest)

ConnectServerReply = _reflection.GeneratedProtocolMessageType('ConnectServerReply', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTSERVERREPLY,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:alpha.server.ConnectServerReply)
  ))
_sym_db.RegisterMessage(ConnectServerReply)

EntityMessage = _reflection.GeneratedProtocolMessageType('EntityMessage', (_message.Message,), dict(
  DESCRIPTOR = _ENTITYMESSAGE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:alpha.server.EntityMessage)
  ))
_sym_db.RegisterMessage(EntityMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))
# @@protoc_insertion_point(module_scope)
