# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='alpha.server',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x0c\x61lpha.server\"\x06\n\x04Void\"9\n\x14\x43onnectServerRequest\x12\x10\n\x08\x65ntityid\x18\x01 \x01(\x05\x12\x0f\n\x07\x61uthmsg\x18\x02 \x01(\t\"8\n\x12\x43onnectServerReply\x12\x10\n\x08\x65ntityid\x18\x01 \x01(\x05\x12\x10\n\x08\x65xtramsg\x18\x02 \x01(\t\"?\n\rEntityMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\tB\x03\x90\x01\x01\x62\x06proto3')
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='alpha.server.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=36,
)


_CONNECTSERVERREQUEST = _descriptor.Descriptor(
  name='ConnectServerRequest',
  full_name='alpha.server.ConnectServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entityid', full_name='alpha.server.ConnectServerRequest.entityid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authmsg', full_name='alpha.server.ConnectServerRequest.authmsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=95,
)


_CONNECTSERVERREPLY = _descriptor.Descriptor(
  name='ConnectServerReply',
  full_name='alpha.server.ConnectServerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entityid', full_name='alpha.server.ConnectServerReply.entityid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extramsg', full_name='alpha.server.ConnectServerReply.extramsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=153,
)


_ENTITYMESSAGE = _descriptor.Descriptor(
  name='EntityMessage',
  full_name='alpha.server.EntityMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='alpha.server.EntityMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='alpha.server.EntityMessage.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='alpha.server.EntityMessage.parameters', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=218,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['ConnectServerRequest'] = _CONNECTSERVERREQUEST
DESCRIPTOR.message_types_by_name['ConnectServerReply'] = _CONNECTSERVERREPLY
DESCRIPTOR.message_types_by_name['EntityMessage'] = _ENTITYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:alpha.server.Void)
  ))
_sym_db.RegisterMessage(Void)

ConnectServerRequest = _reflection.GeneratedProtocolMessageType('ConnectServerRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTSERVERREQUEST,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:alpha.server.ConnectServerRequest)
  ))
_sym_db.RegisterMessage(ConnectServerRequest)

ConnectServerReply = _reflection.GeneratedProtocolMessageType('ConnectServerReply', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTSERVERREPLY,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:alpha.server.ConnectServerReply)
  ))
_sym_db.RegisterMessage(ConnectServerReply)

EntityMessage = _reflection.GeneratedProtocolMessageType('EntityMessage', (_message.Message,), dict(
  DESCRIPTOR = _ENTITYMESSAGE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:alpha.server.EntityMessage)
  ))
_sym_db.RegisterMessage(EntityMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))
# @@protoc_insertion_point(module_scope)
