
FD_TYPE_ACCEPT		= 1
FD_TYPE_CONNECT		= 2
FD_TYPE_READ		= 3
FD_TYPE_CLOSE		= 4

FD_TYPE_CLIENT		= 11
FD_TYPE_SERVER		= 12
FD_TYPE_TIMER		= 13


#mongodb operation
FIND_DOC_OP = 1
UPDATE_DOC_OP = 2
INSERT_DOC_OP = 3